simplified Transpose ambiguity handling
Requires all of these because, if not dimension-specific, we get:

```julia
MethodError: *(::Transpose{Float64,Array{Float64,2}}, ::TrackedArray{…,Array{Float64,1}}) is ambiguous. Candidates:
  *(x::Transpose{T,#s40} where #s40<:(AbstractArray{T,N} where N), y::TrackedArray) where T in Tracker at C:\Users\accou\.julia\dev\Tracker\src\lib\array.jl:391
  *(x::AbstractArray{T,2} where T, y::TrackedArray{T,1,A} where A where T) in Tracker at C:\Users\accou\.julia\dev\Tracker\src\lib\array.jl:383
  *(transA::Transpose{#s623,#s622} where #s622<:AbstractArray{T,2} where #s623, x::AbstractArray{S,1}) where {T, S} in LinearAlgebra at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\matmul.jl:84
Possible fix, define
  *(::Transpose{T,#s622} where #s622<:AbstractArray{T,2}, ::TrackedArray{S,1,A} where A<:AbstractArray{S,1})
```